CREATE TABLE documents (
  id INTEGER NOT NULL PRIMARY KEY,
  title VARCHAR NOT NULL,
  content TEXT NOT NULL
);

CREATE TABLE molecules (
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  smiles VARCHAR NOT NULL
);

CREATE TABLE proteins (
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  sequence TEXT
);